name: Zig CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Zig
      run: |
        wget https://ziglang.org/builds/zig-linux-x86_64-0.11.0-dev.3132+465272921.tar.xz
        tar -xf zig-linux-x86_64-0.11.0-dev.3132+465272921.tar.xz
        sudo mv zig-linux-x86_64-0.11.0-dev.3132+465272921 $HOME/zig
        $HOME/zig/zig version

    - name: Build and test
      run: |
        $HOME/zig/zig build
        $HOME/zig/zig build test
